name: run-tests

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: ["11.*", "12.*", "13.*"]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: "13.*"
            php: 8.2

    name: L${{ matrix.laravel }} - P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, mysql, mysqli, pdo_mysql
          coverage: none

      - name: Cache dependencies installed with composer
        uses: actions/cache@v6
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php }}-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-${{ matrix.laravel }}-composer-

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
